# -*- coding: utf-8 -*-
"""Movie_Recommendation_System_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QByK-AXwlN77igI1lQfhAsaCVASm2567

# **Movie Recommendation System Project (Rule Based)**
"""

import pandas as pd
import re
from google.colab import files

upload = files.upload()
df_rating = pd.read_csv("ratings_small.csv", usecols=['movieId', 'rating'])

uploaded = files.upload()
df_movie = pd.read_csv('movies_metadata.csv', usecols=['id', 'title', 'genres'])

upload = files.upload()
df_link = pd.read_csv("links_small.csv", usecols=['movieId', 'tmdbId'])

df_rating.info()

df_link.info()

df_movie.info()

df_movie['id'] = pd.to_numeric(df_movie['id'], errors='coerce')
df_movie = df_movie.dropna(subset=['id'])
df_movie['id'] = df_movie['id'].astype(int)
df_movie.info()

df_link.isnull().sum()
df_link = df_link.dropna(subset=['tmdbId'])
df_link['tmdbId'] = df_link['tmdbId'].astype(int)
df_link['tmdbId'] = df_link['tmdbId'].unique()

rating_link = pd.merge(df_rating, df_link, on='movieId')
df = pd.merge(rating_link, df_movie, left_on='tmdbId', right_on='id')
df.info()

df = df[['title', 'genres', 'rating']]
df.info()
df.head()

df['genre_names'] = df['genres'].apply(lambda x: re.findall(r"'name': '([^']+)'", x))
df = df.explode('genre_names')
df = df.drop('genres', axis=1)
df.head()

print(df['genre_names'].dropna().unique())

user_input = input("\nEnter which Categories Movies Would you like to watch Today from above list of genre (comma-separated): \n").strip()
pref_gen = [genre.strip().title() for genre in user_input.split(',')]

filtered_df = df[df['genre_names'].isin(pref_gen)]
filtered_df = filtered_df.sort_values(by='rating', ascending=False)
top_5 = filtered_df[['title', 'genre_names', 'rating']].head(5)

print("\nTop Movie Recommendations Based on Your Preferred Genres:\n")
for i, row in top_5.iterrows():
    print(f"{row['title']} (Genre: {row['genre_names']}, Rating: {row['rating']})\n")